### ISSUE TITLE
Issues loading optimizer state, training further under pytorch 1.12.0

### ISSUE THREAD

**Issue by mdmarti** [pearsonlab/autoencoded-vocal-analysis#6]
Howdy! When using torch=1.12.0, [this issue](https://github.com/pytorch/pytorch/issues/80809) comes up. To avoid this, I think we could 
1. require versions other than 1.12.0,
2. only load optimizer state if torch version != 1.12.0
3.  set capturable=True, which looks like it slows down training.

Any preferences among these? Any other solutions that would be better?

**Comment by NickleDave** [comment]
Just curious: is there a reason you can't use 1.12.1 that fixes the regression?
https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598

You could change
https://github.com/pearsonlab/autoencoded-vocal-analysis/blob/a07d8ab75fa32990be9ed083f749f9cbdee34517/setup.py#L24
to
```
torch>=1.1, !=1.12.0
```
so that users don't face the same issue

**Comment by mdmarti** [comment]
We can - I'm asking if that would be the best fix, or if there are other solutions that would be preferable. Thank you for the suggestion!

**Comment by jackgoffinet** [comment]
Hmmm, thanks @mdmarti! If I understood the thread ([here](https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598)), this is a PyTorch issue that will be fixed in 1.12.1, so it's only an issue with torch 1.12.0. If that's the case, I like @NickleDave's suggestion of just changing the requirements in ``setup.py``, so option 1. Option 2 seems a bit hacky to me and we probably don't want to slow down training with the ``capturable`` flag if it can be helped.
